version: '3'
services:
  kanboard:
    container_name: kanboard
    restart: always
    image: kanboard/kanboard:${kanboard_version}
    ports:
     - "80:80"
    networks:
      - kanboard_net
    depends_on:
      - db
    environment:
      DB_DRIVER: postgres
      DB_HOSTNAME: db
      DB_USERNAME: ${postgres_user}
      DB_PASSWORD: ${postgres_password}
    volumes:
     - ./data:/var/www/app/data
     - ./plugins:/var/www/app/plugins
     - ./config.php:/var/www/app/config.php
  db:
    container_name: kanboard-db
    restart: always
    image: postgres:${postgres_version}
    expose:
      - "5432"
    ports:
      - "5432:5432"
    networks:
      - kanboard_net
    environment:
      POSTGRES_USER: ${postgres_user}
      POSTGRES_PASSWORD: ${postgres_password}
      PGDATA: /var/lib/postgresql/data/pg_data
    volumes:
      - ./db:/var/lib/postgresql/data

networks:
  kanboard_net:
    driver: bridge
